import { defineConfig, devices } from '@playwright/test';
import path from 'path';

/**
 * Auto-generated by AutoTestGen
 * Playwright configuration for TypeScript project
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './src/tests',
  timeout: 30 * 1000,
  expect: { timeout: 5000 },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,

  reporter: [
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
    ['list'],
    ['json', { outputFile: 'playwright-report/results.json' }],
  ],

  use: {
    baseURL: process.env.BASE_URL,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'on-first-retry',
    actionTimeout: 10 * 1000,
    navigationTimeout: 30 * 1000,
  },

  projects: [
    // Project 1: Auth Setup (runs once before all tests)
    {
      name: 'setup',
      testMatch: /global-setup\.ts/,
    },
    // Project 2: Authenticated Tests (all generated tests run here)
    {
      name: 'authenticated-chromium',
      use: {
        ...devices['Desktop Chrome'],
        storageState: path.join(__dirname, 'output/auth/storageState.json'),
      },
      dependencies: ['setup'],
      testIgnore: /global-setup\.ts/,
    },
  ],

  outputDir: 'test-results',
});
