// Auto-generated by AutoTestGen
// Custom test fixtures — import { test, expect } from './fixtures' in all spec files
// This extends the base Playwright test with shared context and utilities

import { test as base, expect, Browser, BrowserContext, Page } from '@playwright/test';
import path from 'path';

const STORAGE_STATE = path.join(__dirname, '../../output/auth/storageState.json');

type AuthFixtures = {
  authenticatedPage: Page;
  authenticatedContext: BrowserContext;
};

export const test = base.extend<AuthFixtures>({
  authenticatedContext: async ({ browser }: { browser: Browser }, use: (context: BrowserContext) => Promise<void>) => {
    const context = await browser.newContext({ storageState: STORAGE_STATE });
    await use(context);
    await context.close();
  },

  authenticatedPage: async ({ authenticatedContext }: { authenticatedContext: BrowserContext }, use: (page: Page) => Promise<void>) => {
    const page = await authenticatedContext.newPage();
    await use(page);
  },
});

export { expect };
