// Auto-generated by AutoTestGen — BasePage
// All generated Page Object Models extend this class

import { Page, Locator } from '@playwright/test';

export abstract class BasePage {
  protected readonly page: Page;
  readonly url: string;

  constructor(page: Page, url: string) {
    this.page = page;
    this.url = url;
  }

  async navigate(): Promise<void> {
    await this.page.goto(this.url);
    await this.waitForPageLoad();
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('networkidle');
  }

  async getPageTitle(): Promise<string> {
    return await this.page.title();
  }

  async getHeading(): Promise<string> {
    return (await this.page.locator('h1').first().textContent()) ?? '';
  }

  async isOnPage(urlFragment: string): Promise<boolean> {
    return this.page.url().includes(urlFragment);
  }

  async waitForUrl(urlFragment: string): Promise<void> {
    await this.page.waitForURL(`**${urlFragment}**`);
  }

  async getToastMessage(): Promise<string> {
    const toast = this.page
      .locator('[role="alert"], .toast, .notification, .snackbar, .alert')
      .first();
    await toast.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
    return (await toast.textContent()) ?? '';
  }

  async getSuccessMessage(): Promise<string> {
    const success = this.page
      .locator('[role="alert"].success, .success-message, .alert-success')
      .first();
    await success.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
    return (await success.textContent()) ?? '';
  }

  async getErrorMessage(): Promise<string> {
    const error = this.page
      .locator('[role="alert"].error, .error-message, .alert-danger, .alert-error')
      .first();
    return (await error.textContent()) ?? '';
  }

  async scrollToElement(locator: Locator): Promise<void> {
    await locator.scrollIntoViewIfNeeded();
  }

  async waitForSpinnerToDisappear(): Promise<void> {
    const spinner = this.page.locator('.spinner, .loading, [aria-busy="true"]');
    await spinner.waitFor({ state: 'hidden', timeout: 15000 }).catch(() => {});
  }
}
