// Auto-generated by AutoTestGen — BasePage (JavaScript)
// All generated Page Object Models extend this class

class BasePage {
  constructor(page, url) {
    this.page = page;
    this.url = url;
  }

  async navigate() {
    await this.page.goto(this.url);
    await this.waitForPageLoad();
  }

  async waitForPageLoad() {
    await this.page.waitForLoadState('networkidle');
  }

  async getPageTitle() {
    return await this.page.title();
  }

  async getHeading() {
    return (await this.page.locator('h1').first().textContent()) ?? '';
  }

  async isOnPage(urlFragment) {
    return this.page.url().includes(urlFragment);
  }

  async waitForUrl(urlFragment) {
    await this.page.waitForURL(`**${urlFragment}**`);
  }

  async getToastMessage() {
    const toast = this.page
      .locator('[role="alert"], .toast, .notification, .snackbar')
      .first();
    await toast.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
    return (await toast.textContent()) ?? '';
  }

  async getErrorMessage() {
    const error = this.page
      .locator('[role="alert"].error, .error-message, .alert-danger')
      .first();
    return (await error.textContent()) ?? '';
  }

  async waitForSpinnerToDisappear() {
    const spinner = this.page.locator('.spinner, .loading, [aria-busy="true"]');
    await spinner.waitFor({ state: 'hidden', timeout: 15000 }).catch(() => {});
  }
}

module.exports = { BasePage };
