// Auto-generated by AutoTestGen — Shared Test Utilities
// Import these helpers in data factory files and test files

export const TestUtils = {

  /** Returns a date string N days from today in YYYY-MM-DD format */
  getRelativeDate(daysFromToday: number): string {
    const date = new Date();
    date.setDate(date.getDate() + daysFromToday);
    return date.toISOString().split('T')[0];
  },

  /** Returns today's date in YYYY-MM-DD format */
  today(): string {
    return new Date().toISOString().split('T')[0];
  },

  /** Generates a string of exactly the given length using the given character */
  exactLength(length: number, char = 'A'): string {
    return char.repeat(length);
  },

  /** Generates a random alphanumeric string of given length */
  randomString(length: number): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  },

  /** Returns a valid test email that is unique per run */
  testEmail(prefix = 'automation'): string {
    return `${prefix}+${Date.now()}@example.com`;
  },

  /** Returns a valid future date string N days from today */
  futureDate(days = 30): string {
    return TestUtils.getRelativeDate(days);
  },

  /** Returns a valid past date string N days before today */
  pastDate(days = 1): string {
    return TestUtils.getRelativeDate(-days);
  },

  /** Pads a number to a given length with leading zeros */
  padNumber(num: number, length = 3): string {
    return String(num).padStart(length, '0');
  },
};
