// Auto-generated by AutoTestGen — Shared Test Utilities (JavaScript)

const TestUtils = {

  /** Returns a date string N days from today in YYYY-MM-DD format */
  getRelativeDate(daysFromToday) {
    const date = new Date();
    date.setDate(date.getDate() + daysFromToday);
    return date.toISOString().split('T')[0];
  },

  today() {
    return new Date().toISOString().split('T')[0];
  },

  exactLength(length, char = 'A') {
    return char.repeat(length);
  },

  randomString(length) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  },

  testEmail(prefix = 'automation') {
    return `${prefix}+${Date.now()}@example.com`;
  },

  futureDate(days = 30) {
    return TestUtils.getRelativeDate(days);
  },

  pastDate(days = 1) {
    return TestUtils.getRelativeDate(-days);
  },
};

module.exports = { TestUtils };
